Repository sbt/sbt, pull requests merged in 2018-07, with the labels that each got.

#4239 LM 1.2.0-M3
  build.sbt
  project/Dependencies.scala
  sbt/src/main/scala/Import.scala
Labels: in progress

#4245 Select most recent JDK
  main/src/main/scala/sbt/internal/CrossJava.scala
  main/src/test/scala/sbt/internal/CrossJavaTest.scala
Labels: ready

#4246 Defer deprecation warn of last-grep/load-failed until they are used
  main/src/main/scala/sbt/Main.scala
Labels: Regression, in progress

#4250 Prevent Output panel from stealing focus
  vscode-sbt-scala/client/package-lock.json
  vscode-sbt-scala/client/package.json
  vscode-sbt-scala/client/src/extension.ts
Labels: in progress

#4251 fix typo
  PROFILING.md
  main/src/main/scala/sbt/internal/CrossJava.scala
Labels: in progress

#4253 use val instead of var
  internal/util-collection/src/main/scala/sbt/internal/util/INode.scala
Labels: in progress

#4252 use Java 7 and 8 features
  testing/agent/src/main/java/sbt/ForkMain.java
Labels: in progress

#4254 use SAM type
  core-macros/src/main/scala/sbt/internal/util/appmacro/Instance.scala
  internal/util-collection/src/main/scala/sbt/util/Show.scala
  main-actions/src/main/scala/sbt/TestResultLogger.scala
  main-settings/src/main/scala/sbt/Reference.scala
  main-settings/src/main/scala/sbt/std/TaskMacro.scala
  main/src/main/scala/sbt/Main.scala
  sbt/src/main/scala/AllSyntax.scala
Labels: in progress

#4256 correspond file names and class names, packages and directories
  main/src/main/scala/sbt/TemplateCommandUtil.scala
  main/src/main/scala/sbt/internal/DslEntry.scala
  main/src/main/scala/sbt/plugins/Giter8TemplatePlugin.scala
  sbt/src/main/scala/sbt/AllSyntax.scala
  sbt/src/main/scala/sbt/Import.scala
Labels: in progress

#4255 remove unused project/SiteMap.scala
  project/SiteMap.scala
Labels: in progress

#4257 simplify build settings. sbt 1.x no longer support old scala versions
  project/Dependencies.scala
  project/NightlyPlugin.scala
  project/Util.scala
Labels: in progress

#4258 scripted-sbt-redux
  build.sbt
  main/src/main/scala/sbt/Defaults.scala
  project/Scripted.scala
  sbt/src/sbt-test/project/giter8-plugin/build.sbt
  sbt/src/sbt-test/project/giter8-plugin/project/p.sbt
  sbt/src/sbt-test/project/giter8-plugin/test
  scripted-plugin/src/main/scala/sbt/ScriptedPlugin.scala
  scripted-sbt-old/src/main/scala/sbt/test/ScriptedTests.scala
  scripted-sbt-redux/NOTICE
  scripted-sbt-redux/src/main/scala/sbt/scriptedtest/BatchScriptRunner.scala
  scripted-sbt-redux/src/main/scala/sbt/scriptedtest/RemoteSbtCreator.scala
  scripted-sbt-redux/src/main/scala/sbt/scriptedtest/SbtHandler.scala
  scripted-sbt-redux/src/main/scala/sbt/scriptedtest/ScriptedTests.scala
Labels: in progress

#4263 sbt-giter8-resolver 0.11.0
  main/src/main/scala/sbt/plugins/Giter8TemplatePlugin.scala
Labels: in progress

#4264 Fixes contains bug
  main/src/main/scala/sbt/internal/CrossJava.scala
  sbt/src/sbt-test/java/cross/changes/build.sbt
  sbt/src/sbt-test/java/cross/test
Labels: in progress

#4265 Zinc 1.2.0-M2
  project/Dependencies.scala
Labels: in progress

#4269 Make ++ fail when it doesn't affect any subprojects
  main/src/main/scala/sbt/Cross.scala
  sbt/src/sbt-test/actions/cross-strict-aggregation/test
Labels: in progress
