Repository sbt/sbt, pull requests merged in 2018-09, with the labels that each got.

#4349 fix branch name in CONTRIBUTING
  CONTRIBUTING.md
Labels: ready

#4343 Publish JUnit reports using a compliant filename
  testing/src/main/scala/sbt/JUnitXmlTestsListener.scala
Labels: ready

#4329 Allow same file to be packaged more than once
  main-actions/src/main/scala/sbt/Package.scala
  notes/1.3.0/enable-multiple-source-file-in-mappings.md
  sbt/src/sbt-test/package/mappings/build.sbt
  sbt/src/sbt-test/package/mappings/test
Labels: review

#4332 Add scalaCompilerBridgeBinaryJar task
  main/src/main/scala/sbt/Defaults.scala
  main/src/main/scala/sbt/Keys.scala
  main/src/main/scala/sbt/internal/ConsoleProject.scala
  sbt/src/sbt-test/dependency-management/compiler-bridge-binary/A.scala
  sbt/src/sbt-test/dependency-management/compiler-bridge-binary/build.sbt
  sbt/src/sbt-test/dependency-management/compiler-bridge-binary/test
Labels: ready

#4346 Fix second part of #4091: server responses should not be broadcasted
  main/src/main/scala/sbt/internal/CommandExchange.scala
Labels: ready

#4351 [1.2.x] Fix second part of #4091: server responses should not be broadcasted
  main/src/main/scala/sbt/internal/CommandExchange.scala
  project/Dependencies.scala
Labels: in progress

#4354 Follow up on Position extension
  main/src/main/scala/sbt/internal/server/LanguageServerReporter.scala
Labels: in progress

#4357 [fport] Follow up on Position extension
  main-actions/src/main/scala/sbt/Package.scala
  main/src/main/scala/sbt/Main.scala
  main/src/main/scala/sbt/internal/server/LanguageServerReporter.scala
  project/Dependencies.scala
  testing/src/main/scala/sbt/JUnitXmlTestsListener.scala
Labels: in progress

#4359 Disable eval-is-safe-and-sound test
  sbt/src/sbt-test/actions/eval-is-safe-and-sound/disabled
Labels: in progress

#4334 Add an implicit class for StateOps
  main-command/src/main/scala/sbt/State.scala
Labels: review

#4355 Allow single-letter aliases
  main/src/main/scala/sbt/Cross.scala
  sbt/src/sbt-test/actions/add-alias/build.sbt
  sbt/src/sbt-test/actions/add-alias/test
Labels: in progress

#4356 Remove old warning about global dir
  main/src/main/scala/sbt/BuildPaths.scala
Labels: in progress

#4341 Add `print` command that mimics `show`, but to standard output, not the logger
  main/src/main/scala/sbt/Main.scala
  main/src/main/scala/sbt/internal/Act.scala
  main/src/main/scala/sbt/internal/CommandStrings.scala
Labels: ready

#4313 Support discovering JDK 11 in JAVA_HOME for CrossJava
  main/src/main/scala/sbt/internal/CrossJava.scala
  main/src/test/scala/sbt/internal/CrossJavaTest.scala
Labels: review

#4365 -Xfatal-warnings in most subprojects
  build.sbt
  core-macros/src/main/scala/sbt/internal/util/appmacro/Instance.scala
  internal/util-complete/src/main/scala/sbt/internal/util/complete/ExampleSource.scala
  internal/util-logic/src/main/scala/sbt/internal/util/logic/Logic.scala
  main-actions/src/main/scala/sbt/Package.scala
  main-settings/src/main/scala/sbt/Structure.scala
  main/src/main/scala/sbt/internal/LibraryManagement.scala
  main/src/test/scala/sbt/internal/TestBuild.scala
  project/Util.scala
  project/plugins.sbt
  protocol/src/main/contraband-scala/sbt/internal/langserver/Diagnostic.scala
  protocol/src/main/contraband-scala/sbt/internal/langserver/InitializeParams.scala
  protocol/src/main/contraband-scala/sbt/internal/langserver/InitializeResult.scala
  protocol/src/main/contraband-scala/sbt/internal/langserver/LogMessageParams.scala
  protocol/src/main/contraband-scala/sbt/internal/langserver/Position.scala
  protocol/src/main/contraband-scala/sbt/internal/langserver/PublishDiagnosticsParams.scala
  protocol/src/main/contraband-scala/sbt/internal/langserver/Range.scala
  protocol/src/main/contraband-scala/sbt/internal/langserver/SaveOptions.scala
  protocol/src/main/contraband-scala/sbt/internal/langserver/ServerCapabilities.scala
  protocol/src/main/contraband-scala/sbt/internal/langserver/TextDocumentIdentifier.scala
  protocol/src/main/contraband-scala/sbt/internal/langserver/TextDocumentPositionParams.scala
  protocol/src/main/contraband-scala/sbt/internal/protocol/JsonRpcNotificationMessage.scala
  protocol/src/main/contraband-scala/sbt/internal/protocol/JsonRpcRequestMessage.scala
  protocol/src/main/contraband-scala/sbt/internal/protocol/JsonRpcResponseError.scala
  protocol/src/main/contraband-scala/sbt/internal/protocol/JsonRpcResponseMessage.scala
  protocol/src/main/contraband-scala/sbt/internal/protocol/PortFile.scala
  run/src/main/contraband-scala/sbt/ForkOptions.scala
  sbt/src/test/scala/sbt/RunFromSourceMain.scala
  scripted-plugin/src/main/scala/sbt/ScriptedPlugin.scala
  tasks/src/main/scala/sbt/ConcurrentRestrictions.scala
  tasks/src/main/scala/sbt/Execute.scala
  testing/src/main/contraband-scala/sbt/protocol/testing/TestItemDetail.scala
  testing/src/main/scala/sbt/JUnitXmlTestsListener.scala
Labels: in progress

#4367 expand tilde prefix
  main/src/main/scala/sbt/BuildPaths.scala
  main/src/test/scala/BuildPathsTest.scala
Labels: review

#4277 port addSbtPluginCommand to sbt 0.13
  main/command/src/main/scala/sbt/BasicCommandStrings.scala
  main/command/src/main/scala/sbt/BasicCommands.scala
  main/command/src/main/scala/sbt/BasicKeys.scala
  main/src/main/scala/sbt/Load.scala
  main/src/main/scala/sbt/Main.scala
Labels: x/waffle

#4368 [0.13] port sddPluginSbtFile command from #4211
  .travis.yml
  main/command/src/main/scala/sbt/BasicCommandStrings.scala
  main/command/src/main/scala/sbt/BasicCommands.scala
  main/command/src/main/scala/sbt/BasicKeys.scala
  main/src/main/scala/sbt/Load.scala
  main/src/main/scala/sbt/Main.scala
  project/build.properties
Labels: in progress

#4369 Implement sequential[B](tasks: Seq[Initialize[Task[B]]])
  main/src/main/scala/sbt/internal/TaskSequential.scala
  notes/1.0.0/fix-task-sequential.markdown
Labels: in progress

#4378 Fix: #4370
  main/src/main/scala/sbt/MainLoop.scala
  sbt/src/server-test/events/build.sbt
  sbt/src/test/scala/sbt/RunFromSourceMain.scala
  sbt/src/test/scala/testpkg/ServerSpec.scala
Labels: ready

#4380 Refactor type parameter names
  build.sbt
  tasks/src/main/scala/sbt/Execute.scala
Labels: in progress

#4377 Scala 2.12.7 and linesIterator
  main-settings/src/main/scala/sbt/InputTask.scala
  main/src/main/scala/sbt/internal/LibraryManagement.scala
  main/src/main/scala/sbt/internal/parser/SbtRefactorings.scala
  main/src/test/scala/sbt/internal/parser/EmbeddedXmlSpec.scala
  main/src/test/scala/sbt/internal/parser/ErrorSpec.scala
  project/Dependencies.scala
Labels: in progress

#4388 [1.2.x] Scala 2.12.7
  main-settings/src/main/scala/sbt/InputTask.scala
  main/src/main/scala/sbt/internal/LibraryManagement.scala
  main/src/main/scala/sbt/internal/parser/SbtRefactorings.scala
  main/src/test/scala/sbt/internal/parser/EmbeddedXmlSpec.scala
  main/src/test/scala/sbt/internal/parser/ErrorSpec.scala
  project/Dependencies.scala
Labels: in progress

#4390 Fix scaladoc for DslAggregate
  main/src/main/scala/sbt/internal/DslEntry.scala
Labels: in progress

#4392 Bump up test frameworks used in scripted tests
  project/Dependencies.scala
  project/NightlyPlugin.scala
  sbt/src/sbt-test/dependency-management/cached-resolution-interproj/multi.sbt
  sbt/src/sbt-test/dependency-management/cross-conflict/build.sbt
  sbt/src/sbt-test/dependency-management/cross-conflict/changes/no-conflict-error.sbt
  sbt/src/sbt-test/dependency-management/cross-conflict/test
  sbt/src/sbt-test/run/fork-loader/build.sbt
  sbt/src/sbt-test/tests/arguments-new/build.sbt
  sbt/src/sbt-test/tests/arguments-new/src/test/scala/ArgumentTest.scala
  sbt/src/sbt-test/tests/arguments-new/test
  sbt/src/sbt-test/tests/arguments/build.sbt
  sbt/src/sbt-test/tests/do-not-discover/build.sbt
  sbt/src/sbt-test/tests/done/build.sbt
  sbt/src/sbt-test/tests/fork-async/build.sbt
  sbt/src/sbt-test/tests/fork-parallel/build.sbt
  sbt/src/sbt-test/tests/fork-test-group-parallel/build.sbt
  sbt/src/sbt-test/tests/fork-uncaught/build.sbt
  sbt/src/sbt-test/tests/fork-uncaught/src/main/scala/Foo.scala
  sbt/src/sbt-test/tests/fork-uncaught/src/test/scala/FooTest.scala
  sbt/src/sbt-test/tests/fork-uncaught/test
  sbt/src/sbt-test/tests/fork-uncaught2/build.sbt
  sbt/src/sbt-test/tests/fork/build.sbt
  sbt/src/sbt-test/tests/fork/src/test/scala/Ensemble.scala
  sbt/src/sbt-test/tests/fork2/build.sbt
  sbt/src/sbt-test/tests/fork2/changes/Test.scala
  sbt/src/sbt-test/tests/it/build.sbt
  sbt/src/sbt-test/tests/junit-xml-report/build.sbt
  sbt/src/sbt-test/tests/nested-inproc-par/build.sbt
  sbt/src/sbt-test/tests/nested-inproc-seq/build.sbt
  sbt/src/sbt-test/tests/nested-subproc/build.sbt
  sbt/src/sbt-test/tests/nested-tests/build.sbt
  sbt/src/sbt-test/tests/one-class-multi-framework/build.sbt
  sbt/src/sbt-test/tests/order/build.sbt
  sbt/src/sbt-test/tests/resources/build.sbt
  sbt/src/sbt-test/tests/scala-instance-classloader/build.sbt
  sbt/src/sbt-test/tests/serial/build.sbt
  sbt/src/sbt-test/tests/setup-cleanup/base.sbt
  sbt/src/sbt-test/tests/setup-cleanup/src/test/scala/CheckSetupCleanup.scala
  sbt/src/sbt-test/tests/single-runner/build.sbt
  sbt/src/sbt-test/tests/specs-run/build.sbt
  sbt/src/sbt-test/tests/t543/build.sbt
  sbt/src/sbt-test/tests/task/build.sbt
  sbt/src/sbt-test/tests/test-exclude/build.sbt
  sbt/src/sbt-test/tests/test-exclude/src/test/scala/Test.scala
  sbt/src/sbt-test/tests/test-quick/build.sbt
  sbt/src/server-test/handshake/build.sbt
Labels: in progress

#4393 Bump tests to 2.12
  sbt/src/sbt-test/source-dependencies/binary/build.sbt
  sbt/src/sbt-test/source-dependencies/continuations/Foo.scala
  sbt/src/sbt-test/source-dependencies/continuations/Use.scala
  sbt/src/sbt-test/source-dependencies/continuations/build.sbt
  sbt/src/sbt-test/source-dependencies/continuations/changes/Def1.scala
  sbt/src/sbt-test/source-dependencies/continuations/changes/Def2.scala
  sbt/src/sbt-test/source-dependencies/continuations/test
  sbt/src/sbt-test/source-dependencies/cross-source/src/main/scala-2.12/B.scala
  sbt/src/sbt-test/source-dependencies/cross-source/test
  sbt/src/sbt-test/source-dependencies/ext/disabled
  sbt/src/sbt-test/source-dependencies/macro-annotation/build.sbt
  sbt/src/sbt-test/source-dependencies/macro-arg-dep-2-11/disabled
  sbt/src/sbt-test/source-dependencies/macro-arg-dep-nested-2-11/disabled
  sbt/src/sbt-test/source-dependencies/macro-arg-dep-nested/build.sbt
  sbt/src/sbt-test/source-dependencies/macro-arg-dep-nested/macro-client/Client.scala
  sbt/src/sbt-test/source-dependencies/macro-arg-dep-nested/macro-client/Foo.scala
  sbt/src/sbt-test/source-dependencies/macro-arg-dep-nested/macro-client/changes/Foo.scala
  sbt/src/sbt-test/source-dependencies/macro-arg-dep-nested/macro-provider/Provider.scala
  sbt/src/sbt-test/source-dependencies/macro-arg-dep-stackoverflow/build.sbt
  sbt/src/sbt-test/source-dependencies/macro-arg-dep/build.sbt
  sbt/src/sbt-test/source-dependencies/macro-arg-dep/macro-client/Client.scala
  sbt/src/sbt-test/source-dependencies/macro-arg-dep/macro-client/Foo.scala
  sbt/src/sbt-test/source-dependencies/macro-arg-dep/macro-client/changes/Foo.scala
  sbt/src/sbt-test/source-dependencies/macro-arg-dep/macro-provider/Provider.scala
  sbt/src/sbt-test/source-dependencies/macro/build.sbt
  sbt/src/sbt-test/source-dependencies/macro/macro-client/Client.scala
  sbt/src/sbt-test/source-dependencies/macro/macro-provider/Provider.scala
  sbt/src/sbt-test/source-dependencies/macro/macro-provider/changes/Provider.scala
Labels: in progress
