Repository sbt/sbt, pull requests merged in 2018-10, with the labels that each got.

#4384 Implementing cancellation requests for LSP server
  main/src/main/scala/sbt/EvaluateTask.scala
  main/src/main/scala/sbt/internal/server/LanguageServerProtocol.scala
  protocol/src/main/contraband-scala/sbt/internal/langserver/CancelRequestParams.scala
  protocol/src/main/contraband-scala/sbt/internal/langserver/codec/CancelRequestParamsFormats.scala
  protocol/src/main/contraband-scala/sbt/internal/langserver/codec/JsonProtocol.scala
  protocol/src/main/contraband/lsp.contra
  sbt/src/server-test/events/Main.scala
  sbt/src/server-test/events/build.sbt
  sbt/src/test/scala/testpkg/ServerSpec.scala
Labels: ready

#4400 [1.2.x] Duplicate reports for backwards-compat adding a name-compliant copy
  testing/src/main/scala/sbt/JUnitXmlTestsListener.scala
Labels: in progress

#4401 Zinc 1.2.3
  project/Dependencies.scala
  testing/src/main/scala/sbt/JUnitXmlTestsListener.scala
Labels: in progress

#4403 Fix resolver for compiler bridge
  main-settings/src/main/scala/sbt/SlashSyntax.scala
  main/src/main/scala/sbt/Defaults.scala
  main/src/main/scala/sbt/Keys.scala
Labels: in progress

#4404 check PluginCross.scala consisntency
  build.sbt
  main/src/main/scala/sbt/PluginCross.scala
  project/Dependencies.scala
Labels: in progress

#4405 [1.2.x] check PluginCross.scala consisntency
  build.sbt
  main/src/main/scala/sbt/PluginCross.scala
  project/Dependencies.scala
Labels: in progress

#4396 "super shell" for sbt
  main-actions/src/main/scala/sbt/Package.scala
  main/src/main/scala/sbt/EvaluateTask.scala
  main/src/main/scala/sbt/internal/Aggregation.scala
  main/src/main/scala/sbt/internal/LibraryManagement.scala
  main/src/main/scala/sbt/internal/TaskProgress.scala
  project/Dependencies.scala
  tasks/src/main/scala/sbt/ExecuteProgress.scala
Labels: in progress

#4409 Include both explicit plugin resolves and boot resolvers
  main/src/main/scala/sbt/Defaults.scala
Labels: in progress

#4406 Bump io
  build.sbt
  main-actions/src/main/scala/sbt/ForkTests.scala
  main-actions/src/main/scala/sbt/compiler/Eval.scala
  main/src/main/scala/sbt/internal/parser/SbtParser.scala
  main/src/test/scala/BuildPathsTest.scala
  project/Dependencies.scala
  run/src/test/scala/sbt/ForkTest.scala
  sbt/src/sbt-test/actions/previous/test
  scripted-sbt-redux/src/main/scala/sbt/scriptedtest/ScriptedTests.scala
  testing/src/main/scala/sbt/TestFramework.scala
Labels: in progress

#4335 Watch improvements
  .travis.yml
  build.sbt
  main-command/src/main/scala/sbt/BasicCommandStrings.scala
  main-command/src/main/scala/sbt/BasicCommands.scala
  main-command/src/main/scala/sbt/BasicKeys.scala
  main-command/src/main/scala/sbt/FileTreeViewConfig.scala
  main-command/src/main/scala/sbt/Watched.scala
  main-command/src/main/scala/sbt/internal/LegacyWatched.scala
  main-command/src/test/scala/sbt/WatchedSpec.scala
  main/src/main/scala/sbt/Defaults.scala
  main/src/main/scala/sbt/Keys.scala
  main/src/main/scala/sbt/Main.scala
  main/src/main/scala/sbt/MainLoop.scala
  main/src/main/scala/sbt/internal/ExternalHooks.scala
  main/src/main/scala/sbt/internal/FileManagement.scala
  main/src/main/scala/sbt/internal/Load.scala
  sbt/src/sbt-test/watch/on-start-watch/build.sbt
  sbt/src/sbt-test/watch/on-start-watch/project/Count.scala
  sbt/src/sbt-test/watch/on-start-watch/src/main/scala/A.scala
  sbt/src/sbt-test/watch/on-start-watch/test
Labels: review

#4418 Interactive
  main-command/src/main/scala/sbt/Watched.scala
  main/src/main/scala/sbt/internal/FileManagement.scala
Labels: in progress

#4419 Fix windows reload loop
  main-command/src/main/scala/sbt/Watched.scala
  main/src/main/scala/sbt/Defaults.scala
Labels: in progress

#4417 fix ServerSpec flaky tests
  sbt/src/test/scala/testpkg/ServerSpec.scala
Labels: review

#4397 [sbt-server] LSP completions support
  build.sbt
  main-command/src/main/scala/sbt/State.scala
  main-command/src/main/scala/sbt/internal/server/ServerHandler.scala
  main/src/main/scala/sbt/EvaluateTask.scala
  main/src/main/scala/sbt/internal/server/LanguageServerProtocol.scala
  main/src/main/scala/sbt/internal/server/NetworkChannel.scala
  protocol/src/main/contraband-scala/sbt/internal/langserver/Command.scala
  protocol/src/main/contraband-scala/sbt/internal/langserver/CompletionContext.scala
  protocol/src/main/contraband-scala/sbt/internal/langserver/CompletionItem.scala
  protocol/src/main/contraband-scala/sbt/internal/langserver/CompletionList.scala
  protocol/src/main/contraband-scala/sbt/internal/langserver/CompletionParams.scala
  protocol/src/main/contraband-scala/sbt/internal/langserver/TextDocumentPositionParams.scala
  protocol/src/main/contraband-scala/sbt/internal/langserver/TextDocumentPositionParamsInterface.scala
  protocol/src/main/contraband-scala/sbt/internal/langserver/TextEdit.scala
  protocol/src/main/contraband-scala/sbt/internal/langserver/codec/CommandFormats.scala
  protocol/src/main/contraband-scala/sbt/internal/langserver/codec/CompletionContextFormats.scala
  protocol/src/main/contraband-scala/sbt/internal/langserver/codec/CompletionItemFormats.scala
  protocol/src/main/contraband-scala/sbt/internal/langserver/codec/CompletionListFormats.scala
  protocol/src/main/contraband-scala/sbt/internal/langserver/codec/CompletionParamsFormats.scala
  protocol/src/main/contraband-scala/sbt/internal/langserver/codec/JsonProtocol.scala
  protocol/src/main/contraband-scala/sbt/internal/langserver/codec/TextDocumentPositionParamsInterfaceFormats.scala
  protocol/src/main/contraband-scala/sbt/internal/langserver/codec/TextEditFormats.scala
  protocol/src/main/contraband-scala/sbt/protocol/CompletionParams.scala
  protocol/src/main/contraband-scala/sbt/protocol/CompletionResponse.scala
  protocol/src/main/contraband-scala/sbt/protocol/codec/CompletionParamsFormats.scala
  protocol/src/main/contraband-scala/sbt/protocol/codec/CompletionResponseFormats.scala
  protocol/src/main/contraband-scala/sbt/protocol/codec/JsonProtocol.scala
  protocol/src/main/contraband/lsp.contra
  protocol/src/main/contraband/server.contra
  sbt/src/server-test/completions/build.sbt
  sbt/src/server-test/completions/src/test/scala/ExampleSpec.scala
  sbt/src/test/scala/testpkg/ServerSpec.scala
Labels: review

#4410 ThisBuild / enableSemanticDB
  main/src/main/scala/sbt/Defaults.scala
  main/src/main/scala/sbt/Keys.scala
  main/src/main/scala/sbt/internal/PluginDiscovery.scala
  main/src/main/scala/sbt/plugins/SemanticdbPlugin.scala
  project/Util.scala
  sbt/src/sbt-test/project/semanticdb/build.sbt
  sbt/src/sbt-test/project/semanticdb/src/main/scala/foo/Test.scala
  sbt/src/sbt-test/project/semanticdb/test
Labels: review

#4424 Set withMetadataDirectory by default, bump to lm 1.2.2
  main/src/main/scala/sbt/Defaults.scala
  project/Dependencies.scala
  sbt/src/sbt-test/dependency-management/cache-update/build.sbt
  sbt/src/sbt-test/dependency-management/cached-resolution-conflicts/multi.sbt
Labels: in progress

#4425 [1.2.x] Fixes cached resolution, and upgrades modules
  main/src/main/scala/sbt/Defaults.scala
  project/Dependencies.scala
  sbt/src/sbt-test/dependency-management/cache-update/build.sbt
  sbt/src/sbt-test/dependency-management/cached-resolution-conflicts/multi.sbt
Labels: in progress

#4436 Close the current global file tree view on unload
  main/src/main/scala/sbt/Main.scala
Labels: in progress
