Repository sbt/sbt, pull requests merged in 2018-11, with the labels that each got.

#4443 Use the classpath obtained by the launcher for metabuild
  main/src/main/scala/sbt/Defaults.scala
  main/src/main/scala/sbt/Keys.scala
  main/src/main/scala/sbt/internal/Load.scala
Labels: in progress

#4431 adding sbt-big to the build
  .gitignore
  build.sbt
  project/plugins.sbt
Labels: review

#4447 Fix '~' for dependent projects with a broken parent (1.2.x)
  .travis.yml
  main/src/main/scala/sbt/Defaults.scala
  sbt/src/sbt-test/watch/watch-sources/build.sbt
  sbt/src/sbt-test/watch/watch-sources/changes/Foo.scala
  sbt/src/sbt-test/watch/watch-sources/child/src/main/scala/Bar.scala
  sbt/src/sbt-test/watch/watch-sources/parent/src/main/scala/Foo.scala
  sbt/src/sbt-test/watch/watch-sources/project/plugin.sbt
  sbt/src/sbt-test/watch/watch-sources/test
Labels: in progress

#4449 Fix '~' for dependent projects with a broken parent
  main/src/main/scala/sbt/Defaults.scala
  sbt/src/sbt-test/watch/watch-sources/build.sbt
  sbt/src/sbt-test/watch/watch-sources/changes/Foo.scala
  sbt/src/sbt-test/watch/watch-sources/child/src/main/scala/Bar.scala
  sbt/src/sbt-test/watch/watch-sources/parent/src/main/scala/Foo.scala
  sbt/src/sbt-test/watch/watch-sources/project/plugin.sbt
  sbt/src/sbt-test/watch/watch-sources/test
Labels: in progress

#4456 Multi command
  main-command/src/main/scala/sbt/BasicCommands.scala
  main-command/src/main/scala/sbt/Watched.scala
  main-command/src/test/scala/sbt/MultiParserSpec.scala
  main/src/main/scala/sbt/Main.scala
  sbt/src/sbt-test/actions/multi-command/build.sbt
  sbt/src/sbt-test/actions/multi-command/project/Build.scala
  sbt/src/sbt-test/actions/multi-command/test
  sbt/src/sbt-test/watch/watch-parser/build.sbt
  sbt/src/sbt-test/watch/watch-parser/project/Build.scala
  sbt/src/sbt-test/watch/watch-parser/test
Labels: in progress

#4462 Discover Oracle JDK installed in /opt
  main/src/main/scala/sbt/internal/CrossJava.scala
  main/src/test/scala/sbt/internal/CrossJavaTest.scala
Labels: ready

#4465 [fport] Ignore files in scripted group dirs
  scripted-sbt-redux/src/main/scala/sbt/scriptedtest/ScriptedTests.scala
Labels: in progress

#4468 Update semanticdb-scalac to v4.1.0
  main/src/main/scala/sbt/plugins/SemanticdbPlugin.scala
Labels: ready

#4467 use AdoptOpenJDK 8 on Travis CI
  .travis.yml
Labels: in progress

#4470 [0.13] give up on publishing using JDK 1.6
  .java-version
  build.sbt
  project/Release.scala
  project/plugins.sbt
Labels: in progress

#4471 [1.2.x] fix nightly
  project/Dependencies.scala
Labels: in progress

#4466 [1.2.x] drop notification override
  .travis.yml
Labels: in progress

#4454 Fix prompt for task progress
  build.sbt
  internal/util-complete/src/main/scala/sbt/internal/util/LineReader.scala
  main/src/main/scala/sbt/internal/Aggregation.scala
  main/src/main/scala/sbt/internal/TaskProgress.scala
  project/Dependencies.scala
Labels: review

#4473 bump util, lm, and zinc
  build.sbt
  project/Dependencies.scala
  scripted-sbt-redux/src/main/scala/sbt/scriptedtest/ScriptedTests.scala
Labels: in progress
