Repository sbt/sbt, pull requests merged in 2018-03, with the labels that each got.

#3996 Fix #3990: Add CLA instruction to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: ready

#3988 Cleanups from my recent work in scripted
  build.sbt
  internal/util-collection/src/main/scala/sbt/internal/util/Attributes.scala
  internal/util-complete/src/test/scala/sbt/complete/FileExamplesTest.scala
  main-command/src/main/scala/sbt/State.scala
  main-command/src/main/scala/xsbt/IPC.scala
  main-settings/src/main/scala/sbt/std/InputConvert.scala
  main-settings/src/main/scala/sbt/std/InputWrapper.scala
  main-settings/src/test/scala/sbt/std/neg/TaskNegSpec.scala
  main/src/main/scala/sbt/Extracted.scala
  main/src/main/scala/sbt/Main.scala
  main/src/main/scala/sbt/ScriptedPlugin.scala
  main/src/main/scala/sbt/internal/BuildStructure.scala
  project/PublishBinPlugin.scala
  project/Scripted.scala
  sbt/src/sbt-test/actions/add-alias/A.scala
  sbt/src/sbt-test/actions/add-alias/build.sbt
  sbt/src/sbt-test/actions/doc-scala-instance/build.sbt
  sbt/src/sbt-test/actions/generator/build.sbt
  sbt/src/sbt-test/actions/run-task/build.sbt
  scripted/sbt/src/main/scala/sbt/scriptedtest/BatchScriptRunner.scala
  scripted/sbt/src/main/scala/sbt/scriptedtest/SbtHandler.scala
  scripted/sbt/src/main/scala/sbt/scriptedtest/ScriptedTests.scala
  tasks-standard/src/test/scala/TaskRunnerFork.scala
Labels: in progress

#3987 Document RichInitX classes
  main-settings/src/main/scala/sbt/Structure.scala
Labels: in progress

#3997 Fix race condition in non-forked, parallel tests.
  build.sbt
  main-command/src/main/scala/sbt/internal/server/Server.scala
  testing/src/main/scala/sbt/TestStatusReporter.scala
Labels: in progress

#3998 Add test to confirm leak is gone
  sbt/src/sbt-test/project/cross-source/build.sbt
  sbt/src/sbt-test/project/cross-source/p1/src/main/scala-2.10/B.scala
  sbt/src/sbt-test/project/cross-source/p1/src/main/scala/A.scala
  sbt/src/sbt-test/project/cross-source/p2/src/main/scala-2.10/B.scala
  sbt/src/sbt-test/project/cross-source/p2/src/main/scala/A.scala
  sbt/src/sbt-test/project/cross-source/p3/src/main/scala-2.10/B.scala
  sbt/src/sbt-test/project/cross-source/p3/src/main/scala/A.scala
  sbt/src/sbt-test/project/cross-source/p4/src/main/scala-2.10/B.scala
  sbt/src/sbt-test/project/cross-source/p4/src/main/scala/A.scala
  sbt/src/sbt-test/project/cross-source/test
Labels: in progress

#3994 Add more configuration axis ScopeFilter factory methods
  main/src/main/scala/sbt/Defaults.scala
  main/src/main/scala/sbt/ScopeFilter.scala
  notes/1.1.2/in_configurations_scope_filter_factories.md
Labels: ready

#3995 Filter incompatible aggregates in cross switch commands
  main/src/main/scala/sbt/Cross.scala
  notes/1.2.0/cross-strict-aggregation.md
  sbt/src/sbt-test/actions/cross-strict-aggregation/build.sbt
  sbt/src/sbt-test/actions/cross-strict-aggregation/core/A.scala
  sbt/src/sbt-test/actions/cross-strict-aggregation/module/B.scala
  sbt/src/sbt-test/actions/cross-strict-aggregation/test
Labels: ready

#3999 [bport] Cache watch service
  main-command/src/main/scala/sbt/Watched.scala
Labels: in progress

#3975 make sbt server extensible
  build.sbt
  main-command/src/main/scala/sbt/BasicKeys.scala
  main-command/src/main/scala/sbt/internal/server/ServerHandler.scala
  main/src/main/scala/sbt/Defaults.scala
  main/src/main/scala/sbt/Keys.scala
  main/src/main/scala/sbt/Project.scala
  main/src/main/scala/sbt/internal/CommandExchange.scala
  main/src/main/scala/sbt/internal/server/LanguageServerProtocol.scala
  main/src/main/scala/sbt/internal/server/NetworkChannel.scala
  sbt/src/server-test/handshake/build.sbt
  sbt/src/test/scala/sbt/ServerSpec.scala
Labels: in progress

#3989 Cleanup some parts of the LSP impl
  main/src/main/scala/sbt/internal/server/LanguageServerProtocol.scala
  protocol/src/main/scala/sbt/protocol/Serialization.scala
Labels: in progress

#3991 Add an optional exitCode to ExecStatusEvent so clients can use it
  build.sbt
  main-command/src/main/contraband-scala/sbt/CommandSource.scala
  main-command/src/main/contraband-scala/sbt/Exec.scala
  main-command/src/main/scala/sbt/internal/server/Server.scala
  main/src/main/scala/sbt/MainLoop.scala
  main/src/main/scala/sbt/internal/server/NetworkChannel.scala
  project/plugins.sbt
  protocol/src/main/contraband-scala/sbt/internal/langserver/ClientCapabilities.scala
  protocol/src/main/contraband-scala/sbt/internal/langserver/Diagnostic.scala
  protocol/src/main/contraband-scala/sbt/internal/langserver/InitializeParams.scala
  protocol/src/main/contraband-scala/sbt/internal/langserver/InitializeResult.scala
  protocol/src/main/contraband-scala/sbt/internal/langserver/Location.scala
  protocol/src/main/contraband-scala/sbt/internal/langserver/LogMessageParams.scala
  protocol/src/main/contraband-scala/sbt/internal/langserver/Position.scala
  protocol/src/main/contraband-scala/sbt/internal/langserver/PublishDiagnosticsParams.scala
  protocol/src/main/contraband-scala/sbt/internal/langserver/Range.scala
  protocol/src/main/contraband-scala/sbt/internal/langserver/SaveOptions.scala
  protocol/src/main/contraband-scala/sbt/internal/langserver/SbtExecParams.scala
  protocol/src/main/contraband-scala/sbt/internal/langserver/ServerCapabilities.scala
  protocol/src/main/contraband-scala/sbt/internal/langserver/TextDocumentIdentifier.scala
  protocol/src/main/contraband-scala/sbt/internal/langserver/TextDocumentPositionParams.scala
  protocol/src/main/contraband-scala/sbt/internal/langserver/TextDocumentSyncOptions.scala
  protocol/src/main/contraband-scala/sbt/internal/protocol/InitializeOption.scala
  protocol/src/main/contraband-scala/sbt/internal/protocol/JsonRpcNotificationMessage.scala
  protocol/src/main/contraband-scala/sbt/internal/protocol/JsonRpcRequestMessage.scala
  protocol/src/main/contraband-scala/sbt/internal/protocol/JsonRpcResponseError.scala
  protocol/src/main/contraband-scala/sbt/internal/protocol/JsonRpcResponseMessage.scala
  protocol/src/main/contraband-scala/sbt/internal/protocol/PortFile.scala
  protocol/src/main/contraband-scala/sbt/internal/protocol/TokenFile.scala
  protocol/src/main/contraband-scala/sbt/protocol/ChannelAcceptedEvent.scala
  protocol/src/main/contraband-scala/sbt/protocol/ExecCommand.scala
  protocol/src/main/contraband-scala/sbt/protocol/ExecStatusEvent.scala
  protocol/src/main/contraband-scala/sbt/protocol/ExecutionEvent.scala
  protocol/src/main/contraband-scala/sbt/protocol/InitCommand.scala
  protocol/src/main/contraband-scala/sbt/protocol/LogEvent.scala
  protocol/src/main/contraband-scala/sbt/protocol/SettingQuery.scala
  protocol/src/main/contraband-scala/sbt/protocol/SettingQueryFailure.scala
  protocol/src/main/contraband-scala/sbt/protocol/SettingQuerySuccess.scala
  protocol/src/main/contraband-scala/sbt/protocol/codec/ExecStatusEventFormats.scala
  protocol/src/main/contraband/server.contra
  protocol/src/main/scala/sbt/internal/langserver/ErrorCodes.scala
  run/src/main/contraband-scala/sbt/ForkOptions.scala
  run/src/main/scala/sbt/OutputStrategy.scala
  testing/src/main/contraband-scala/sbt/protocol/testing/EndTestGroupErrorEvent.scala
  testing/src/main/contraband-scala/sbt/protocol/testing/EndTestGroupEvent.scala
  testing/src/main/contraband-scala/sbt/protocol/testing/StartTestGroupEvent.scala
  testing/src/main/contraband-scala/sbt/protocol/testing/TestCompleteEvent.scala
  testing/src/main/contraband-scala/sbt/protocol/testing/TestInitEvent.scala
  testing/src/main/contraband-scala/sbt/protocol/testing/TestItemDetail.scala
  testing/src/main/contraband-scala/sbt/protocol/testing/TestItemEvent.scala
  testing/src/main/contraband-scala/sbt/protocol/testing/TestStringEvent.scala
Labels: in progress

#4019 Improve instruction for locally built sbt in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: ready

#4022 support test compile on saving in vscode
  main/src/main/scala/sbt/internal/server/LanguageServerProtocol.scala
Labels: ready

#4025 Fix handling id in jsonrpc model
  protocol/src/main/scala/sbt/internal/protocol/codec/JsonRpcRequestMessageFormats.scala
  protocol/src/main/scala/sbt/internal/protocol/codec/JsonRpcResponseMessageFormats.scala
  sbt/src/test/scala/sbt/ServerSpec.scala
Labels: hackathon, ready

#4018 Cleanup NetworkChannel
  build.sbt
  main/src/main/scala/sbt/internal/server/LanguageServerProtocol.scala
  main/src/main/scala/sbt/internal/server/NetworkChannel.scala
Labels: in progress

#4016 Make Watched use State#handleError
  build.sbt
  main-command/src/main/scala/sbt/State.scala
  main-command/src/main/scala/sbt/Watched.scala
Labels: in progress

#4017 Cleanup CommandChannel
  build.sbt
  main-command/src/main/scala/sbt/internal/CommandChannel.scala
  main-command/src/main/scala/sbt/internal/ConsoleChannel.scala
  main/src/main/scala/sbt/internal/server/NetworkChannel.scala
Labels: in progress

#4030 Vector 1.1
  sbt/src/sbt-test/tests/fork-async/build.sbt
  sbt/src/sbt-test/tests/fork-async/src/test/scala/ForkAsyncTest.scala
  sbt/src/sbt-test/tests/fork-async/test
  testing/agent/src/main/java/sbt/ForkMain.java
Labels: ready

#4033 Fixes new command leaving behind target directory
  main/src/main/scala/sbt/TemplateCommand.scala
Labels: in progress

#4031 bump modules
  main/src/main/scala/sbt/Defaults.scala
  project/Dependencies.scala
Labels: in progress

#4036 Fixes -error not suppressing startup logs
  main/src/main/scala/sbt/internal/LogManager.scala
Labels: in progress

#4040 Dedup keys in SlashSyntaxSpec
  main-settings/src/test/scala/sbt/SlashSyntaxSpec.scala
Labels: in progress

#4046 bump to 1.1.3-SNAPSHOT
  build.sbt
  project/build.properties
Labels: in progress

#4045 Deprecate Scope.transformTaskName
  main-settings/src/main/scala/sbt/Scope.scala
Labels: in progress

#4043 Cleanup test/ParseKey
  main/src/test/scala/ParseKey.scala
Labels: in progress

#4050 Update to Jline 2.14.6
  project/Dependencies.scala
Labels: ready
