Repository sbt/sbt, pull requests merged in 2018-06, with the labels that each got.

#3971 fix getDecoder
  compile/persist/src/main/scala/sbt/inc/Base64.scala
Labels: ready

#4212 Open up setPlugins to private[sbt]
  main/src/main/scala/sbt/Project.scala
Labels: in progress

#4213 Split server unit test on its own
  .travis.yml
  build.sbt
Labels: in progress

#4211 addPluginSbtFile command
  main-command/src/main/scala/sbt/BasicCommandStrings.scala
  main-command/src/main/scala/sbt/BasicCommands.scala
  main-command/src/main/scala/sbt/BasicKeys.scala
  main/src/main/scala/sbt/Main.scala
  main/src/main/scala/sbt/internal/Load.scala
  main/src/test/scala/sbt/internal/server/SettingQueryTest.scala
  notes/1.2.0/add-plugin.md
Labels: in progress

#4215 Use 1.x branch
  CONTRIBUTING.md
Labels: in progress

#4216 Addresses #4206 - Introduces fgRun and fgRunMain
  main/src/main/scala/sbt/Defaults.scala
  main/src/main/scala/sbt/Keys.scala
Labels: hackathon, ready

#4220 Add alternative scripted filenames
  main/src/main/scala/sbt/ScriptedPlugin.scala
  sbt/src/sbt-test/project/test-script-file/build.sbt
  sbt/src/sbt-test/project/test-script-file/test.script
  scripted/sbt/src/main/scala/sbt/scriptedtest/ScriptedTests.scala
Labels: hackathon, ready

#4221 Inspect supports alias
  main/src/main/scala/sbt/Main.scala
  main/src/main/scala/sbt/internal/CommandStrings.scala
  main/src/main/scala/sbt/internal/Inspect.scala
  notes/1.2.0/inspect-alias.md
  sbt/src/sbt-test/project/unified/build.sbt
Labels: hackathon, ready

#4229 IO 1.2.0-M2
  project/Dependencies.scala
  sbt/src/sbt-test/dependency-management/ext-pom-classifier/build.sbt
Labels: in progress

#4217 Use .sbtopts to increase the RAM
  .sbtopts
Labels: hackathon, in progress

#4218 Add doc task to travis-ci
  .travis.yml
Labels: hackathon, ready

#4226 Fix CTRL-C exception
  testing/agent/src/main/java/sbt/ForkMain.java
Labels: ready

#4230 remove gittatributes, assume core.autocrlf=false
  .gitattributes
Labels: ready

#4233 Increase the timeout to 90s
  sbt/src/test/scala/testpkg/ServerSpec.scala
Labels: in progress

#4232 Fixes the stacktrace of run
  build.sbt
  main/src/main/scala/sbt/Defaults.scala
  main/src/main/scala/sbt/internal/LogManager.scala
  run/src/main/scala/sbt/Run.scala
Labels: in progress

#4003 optimize scope delegation
  internal/util-collection/src/main/scala/sbt/internal/util/Settings.scala
  main-settings/src/main/scala/sbt/Scope.scala
Labels: in progress

#4235 Util 1.2.0-M2, LM 1.2.0-M2
  main-settings/src/main/scala/sbt/Scope.scala
  project/Dependencies.scala
Labels: in progress

#4237 Fixes `sbt help new` not working as batch command
  main-command/src/main/scala/sbt/BasicCommandStrings.scala
  main-command/src/main/scala/sbt/BasicCommands.scala
  notes/1.0.3/help-sbt-new.md
  sbt/src/sbt-test/actions/multiple-with-error/test
  sbt/src/sbt-test/project/inside-ci/test
  sbt/src/sbt-test/project/sbt-version-change/test
  sbt/src/sbt-test/project/scripted-bad-def/test
  sbt/src/sbt-test/project/source-plugins/pending
Labels: in progress
