Repository sbt/sbt, pull requests merged in 2019-02, with the labels that each got.

#4534 Misc fixups
  main-settings/src/main/scala/sbt/dsl/LinterLevel.scala
  main-settings/src/main/scala/sbt/std/TaskLinterDSL.scala
  sbt/src/sbt-test/project/unique-settings-computation/project/A.scala
Labels: in progress

#4527 Use custom classloader for scripted tests
  project/Scripted.scala
  sbt/src/sbt-test/dependency-management/cached-resolution-classifier/test
  sbt/src/sbt-test/dependency-management/cached-resolution-conflicts/test
  sbt/src/sbt-test/dependency-management/cached-resolution-interproj/test
  sbt/src/sbt-test/dependency-management/exclude-transitive/test
  sbt/src/sbt-test/dependency-management/ivy-settings-a/test
  sbt/src/sbt-test/dependency-management/mvn-local/disabled
  scripted-sbt-redux/src/main/scala/sbt/scriptedtest/ScriptedTests.scala
Labels: review

#4535 Stamped file
  main-command/src/main/scala/sbt/BasicKeys.scala
  main-command/src/main/scala/sbt/FileTreeViewConfig.scala
  main-command/src/main/scala/sbt/Stamped.scala
  main-command/src/main/scala/sbt/Watched.scala
  main-command/src/main/scala/sbt/internal/FileCacheEntry.scala
  main-command/src/test/scala/sbt/WatchedSpec.scala
  main/src/main/scala/sbt/Defaults.scala
  main/src/main/scala/sbt/Keys.scala
  main/src/main/scala/sbt/Main.scala
  main/src/main/scala/sbt/internal/ExternalHooks.scala
  main/src/main/scala/sbt/internal/FileManagement.scala
Labels: review

#4537 Allow watch loops
  main/src/main/scala/sbt/Defaults.scala
  sbt/src/sbt-test/tests/watch-loop/build.sbt
  sbt/src/sbt-test/tests/watch-loop/project/SourceWrapper.scala
  sbt/src/sbt-test/tests/watch-loop/src/main/scala/Bar.scala
  sbt/src/sbt-test/tests/watch-loop/src/main/scala/Foo.scala
  sbt/src/sbt-test/tests/watch-loop/test
Labels: review

#4533 Add meaningful toString to values in TypeFunctions
  internal/util-collection/src/main/scala/sbt/internal/util/TypeFunctions.scala
Labels: review

#4542 Remove Dotty handling in scalaInstance
  main/src/main/scala/sbt/Defaults.scala
Labels: ready

#4544 Run gc when idle
  main/src/main/scala/sbt/Main.scala
  main/src/main/scala/sbt/internal/CommandExchange.scala
  main/src/main/scala/sbt/internal/GCUtil.scala
Labels: in progress

#4549 Avoid NPE on Run.<init>
  main-actions/src/main/scala/sbt/compiler/Eval.scala
Labels: in progress

#4550 Bump node modules for security fixes
  vscode-sbt-scala/client/package-lock.json
  vscode-sbt-scala/client/package.json
  vscode-sbt-scala/server/package.json
Labels: in progress

#4551 sbt 1.2.8
  project/build.properties
Labels: in progress
